/*Assignment 2: Design a database schema for a library system, including tables, fields, and constraints like NOT NULL, UNIQUE, and CHECK.
 Include primary and foreign keys to establish relationships between tables.*/
create database library_system;
use library_system;

CREATE TABLE BOOKS(
ISBN VARCHAR(30) PRIMARY KEY,
TITLE VARCHAR(100) NOT NULL,
AUTHOR VARCHAR(20) NOT NULL,
PUBLISHER VARCHAR(100) NOT NULL,
PUBLISH_YEAR INT NOT NULL,
QUANTITY INT NOT NULL CHECK(QUANTITY>=0)
);

CREATE TABLE MEMBERS(
MEMBER_ID VARCHAR(20) PRIMARY KEY,
NAME VARCHAR(10) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
EMAIL VARCHAR(30) UNIQUE CHECK (EMAIL LIKE("%@%.%")),
MOBILE_NO BIGINT UNIQUE NOT NULL
);

CREATE TABLE BORROWINGS(
BORROWING_ID INT PRIMARY KEY,
MEMBER_ID VARCHAR(20),
ISBN VARCHAR(30),
BORROW_DATE DATE NOT NULL,
RETURN_DATE DATE NOT NULL,
CONSTRAINT FK_MEMBERID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID), -- FOREIGN KEY REPRESENTS THE RELATIONSHIP BETWEEN TWO OR MORE TABLES
 -- IT WILL MAP TO MEMBER ID OF MEMBERS TABLE
CONSTRAINT FK_ISBN FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) -- IT WILL MAP TO ISBN OF BOOKS TABLE
); 

