/* Compose SQL statements to BEGIN a transaction, INSERT a new record into the 'orders' table, COMMIT the transaction, 
then UPDATE the 'products' table, and ROLLBACK the transaction.*/

USE WIPRO_TRAINING;

SELECT * FROM ORDERS;
START TRANSACTION; -- TRANSACTION BEGINS
SAVEPOINT INITIAL;
-- Inset=rting a record
INSERT INTO ORDERS
VALUES(8,1006,'LAPTOP',576577.88,100);
-- COMMITTING A TRANSACTION
COMMIT;
savepoint BEFOREUPDATE;
-- UPDATING THE TABLE
UPDATE PRODUCTS
SET QUANTITY=QUANTITY-100
WHERE NAME='LAPTOP';
ROLLBACK TO BEFOREUPDATE;